### ISSUE TITLE
question of Vamb

### ISSUE THREAD

**Issue by yuyuyu-fy** [xuehansheng/RepBin#2]
Hello, I'm sorry to bother you to ask me some questions.

How do you run vamb in your paper? As we can see, vamb provides a large number of clusters. How do you choose the minimum overlapping group length? How to ensure the good effect of his F1 value? I use the default parameters to run samples with a minimum length of 1500, and the effect is very poor or even impossible to calculate.

By the way, does repbin need to input the cluster number by itself? If it is convenient, can I ask you for the fastq file of sim5g 10g 20g, or how to download it?
Thank you very much.

**Comment by Vini2** [comment]
Hello @yuyuyu-fy,

Thank you very much for your interest in RepBin.

We ran Vamb only in the co-assembly mode which did not result in many bins as in the multi-sample mode. We had to reduce the batch size (parameter `t`) of Vamb to run on the simulated datasets.

You have to input the number of clusters after calculating it using marker genes. 

I have added the FASTQ files of the Sim-5G and Sim-10G datasets on figshare at [https://figshare.com/projects/RepBin/140858](https://figshare.com/projects/RepBin/140858).

Let me know if you have any further questions.

Best regards,
Vijini

**Comment by yuyuyu-fy** [comment]
Vrey thanks！
